name: Create a new release with release notes from previous pull requests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Build Changelog"
        id: build_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get next release version"
        uses: wemogy/next-version-action@2.0.2
        id: release-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projects: 'Single'
      - name: Create Release
        id: create_release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-version.outputs.next-version }}
          release_name: ${{ steps.release-version.outputs.next-version }}
          body: ${{steps.build_changelog.outputs.changelog}}
      - name: Build and pack
        if: success()
        run: |
          # build application
          dotnet build --configuration Release
          # create zip archive with the built application
          zip -r app.zip /home/runner/work/OfferChecker/OfferChecker/OfferCheckerAPI/bin/Release/net6.0/
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app.zip
          asset_name: app.zip
          asset_content_type: application/zip
